export const GET_POPULAR_MOVIES_SUCCESS = 'GET_POPULAR_MOVIES_SUCCESS';
export const GET_POPULAR_SERIES_SUCCESS='GET_POPULAR_SERIES_SUCCESS';
export const GET_GENRE_FAMILY_SUCCESS='GET_GENRE_FAMILY_SUCCESS';
export const GET_GENRE_DOCUMENTARY_SUCCESS='GET_GENRE_DOCUMENTARY_SUCCESS';
export const GET_GENRE_SUCCESS="GET_GENRE_SUCCESS";
export const GET_LENGUAGE_SUCCESS="GET_LENGUAGE_SUCCESS";